# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_json:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Update JSON resources
    steps:
        - uses: actions/checkout@v1

        - uses: actions/setup-node@v1

        # Updates the JSON for Matt Grant's Discogs Vinyl Wantlist
        - name: Update Discogs Wantlist
          shell: bash
          env:
            DISCOGS_API_KEY: ${{ secrets.DISCOGS_API_KEY }}
          run: curl \
            https://api.discogs.com/users/mattgra/wants?token=$DISCOGS_API_KEY \
            -o _data/vinyl/collection.json \
            | json_pp
        
        # Updates the JSON for Matt Grant's Discogs Vinyl Collection
        - name: Update Discogs Collection
          shell: bash
          env:
            DISCOGS_API_KEY: ${{ secrets.DISCOGS_API_KEY }}
          run: curl \
            https://api.discogs.com/users/mattgra/collection/folders/0/releases?token=$DISCOGS_API_KEY \
            -o _data/vinyl/collection.json \
            | json_pp
        
        - name: Update JSON files
          uses: test-room-7/action-update-file@v1.4.0
          with:
              file-path: |
                _data/vinyl/wantlist.json
                _data/vinyl/collection.json
              commit-msg: Update JSON from Discogs
              github-token: ${{ secrets.GITHUB_TOKEN }}
